### ISSUE TITLE
Netlink load reader accidentally allocates 4GB of memory

### ISSUE THREAD

**Issue by krallin** [google/cadvisor#1182]
I've been observing some odd behaviour when enabling the netlink-based load reader. Across a fleet of ~50 servers, a few of them will end up with cAdvisor allocating several GB of memory (always a multiple of 4GB).

A bit of researched turned up what seems to be the root cause: the netlink reader is accidentally allocating ~4GB of memory (0xfffffff4): 

```
goroutine 163 [running]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc8216ad3c0 sp=0xc8216ad3b8
runtime.mallocgc(0xfffffff4, 0xa4a2a0, 0x1, 0x40)
    /usr/local/go/src/runtime/malloc.go:638 +0x9c4 fp=0xc8216ad490 sp=0xc8216ad3c0
runtime.newarray(0xa4a2a0, 0xfffffff4, 0x411066)
    /usr/local/go/src/runtime/malloc.go:780 +0xc9 fp=0xc8216ad4d0 sp=0xc8216ad490
runtime.makeslice(0xa2f2c0, 0xfffffff4, 0xfffffff4, 0x0, 0x0, 0x0)
    /usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc8216ad520 sp=0xc8216ad4d0
github.com/google/cadvisor/utils/cpuload/netlink.(*Connection).ReadMessage(0xc820393110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/build/gopath/src/github.com/google/cadvisor/utils/cpuload/netlink/conn.go:92 +0x1a6 fp=0xc8216ad5b8 sp=0xc8216ad520
github.com/google/cadvisor/utils/cpuload/netlink.getLoadStats(0xc820640018, 0x1e, 0xc820393110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/build/gopath/src/github.com/google/cadvisor/utils/cpuload/netlink/netlink.go:231 +0x1b6 fp=0xc8216ad6a8 sp=0xc8216ad5b8
github.com/google/cadvisor/utils/cpuload/netlink.(*NetlinkReader).GetCpuLoad(0xc8203ce930, 0xc8202559a0, 0x48, 0xc8206457a0, 0x5a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/build/gopath/src/github.com/google/cadvisor/utils/cpuload/netlink/reader.go:73 +0x33f fp=0xc8216ad7c0 sp=0xc8216ad6a8
github.com/google/cadvisor/manager.(*containerData).updateStats(0xc820207860, 0x0, 0x0)
    /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:508 +0x330 fp=0xc8216adc88 sp=0xc8216ad7c0
github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0xc820207860)
    /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:447 +0x2b fp=0xc8216add10 sp=0xc8216adc88
github.com/google/cadvisor/manager.(*containerData).housekeeping(0xc820207860)
    /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:398 +0x29f fp=0xc8216adf98 sp=0xc8216add10
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8216adfa0 sp=0xc8216adf98
created by github.com/google/cadvisor/manager.(*containerData).Start
    /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:94 +0x41
```

The size of the allocation seems to be [derived from the netlink header](https://github.com/google/cadvisor/blob/a8f595460949547c00b7dc0f5906e905cde38047/utils/cpuload/netlink/conn.go#L92), so one of two things must be happening:
- The kernel is returning the wrong value for the netlink header (sounds a bit unlikely?)
- `binary.Read(self.rbuf, binary.LittleEndian, &msg.Header)` isn't actually reading a netlink message header (i.e. there is something else in the buffer — seems more likely?)

I can repro somewhat consistently across our fleet of instances. Is there something I can do to help track this issue down? (note:  I won't be able to do so for very long, since we'd like to actually ship cAdvisor across said fleet of instances)

Cheers,

**Comment by dashpole** [comment]
Did #1188 address this issue?

**Comment by krallin** [comment]
@dashpole yep
