### ISSUE TITLE
Unable to disable disk metrics using command line flag

### ISSUE THREAD

**Issue by sumeetk-gem** [google/cadvisor#1267]
I am using cAdvisor version v0.23.0, with docker 1.7.1 on CentOS 7.1. 
On trying to disable disk metrics monitoring using `-disable_metrics` flag, I get the following error and cAdvisor exits -

```
#  docker run --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw  --volume=/sys:/sys:ro  --volume=/var/lib/docker/:/var/lib/docker:ro  --publish=9101:8080   --name=cadvisor --privileged=true -it google/cadvisor:latest -disable_metrics disk -housekeeping_interval=10s
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0xb0c8c0, 0xc8201819b0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*metricSetValue).Set(0x15ac528, 0x7ffe0bde0f42, 0x4, 0x0, 0x0)
        /go/src/github.com/google/cadvisor/cadvisor.go:85 +0x1da
flag.(*FlagSet).parseOne(0xc820058060, 0xc8201fe101, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:881 +0xdd9
flag.(*FlagSet).Parse(0xc820058060, 0xc82005c060, 0x4, 0x4, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:900 +0x6e
flag.Parse()
        /usr/local/go/src/flag/flag.go:928 +0x6f
main.main()
        /go/src/github.com/google/cadvisor/cadvisor.go:99 +0x68

```

Description in command help -
```
  -disable_metrics disk
        comma-separated list of metrics to be disabled. Options are disk, `network`, `tcp`. Note: tcp is disabled by default due to high CPU usage. (default {map[tcp:{}]})
```

**Comment by leonardinius** [comment]
I've just experienced the same behavior.

**Comment by timstclair** [comment]
This should be fixed in the latest cAdvisor release. Please respond if that's not the case.
