### ISSUE TITLE
Master Crash + stacktrace

### ISSUE THREAD

**Issue by f0** [google/cadvisor#1310]
the current master (49f3d7ed3d786202ce0ae8d7ff7aa962fea53b93) crashes , the version 0.23.2-7ddf6eb
```
I0524 21:24:47.455933   36794 storagedriver.go:50] Caching stats in memory for 2m0s
I0524 21:24:47.456139   36794 manager.go:138] cAdvisor running in container: "/system.slice/system-sshd.slice/sshd@22685-10.61.112.241"
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0xfba1a0, 0x2a)
        /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 16 [syscall, locked to thread]:
runtime.cgocall(0xaac3c0, 0xc820046bd8, 0x0)
        /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820046b78 sp=0xc820046b48
net._C2func_getaddrinfo(0x7f13280008c0, 0x0, 0xc8202f0810, 0xc82003a058, 0x0, 0x0, 0x0)
        ??:0 +0x55 fp=0xc820046bd8 sp=0xc820046b78
net.cgoLookupIPCNAME(0xea0c40, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc820046d50 sp=0xc820046bd8
net.cgoLookupIP(0xea0c40, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x653d5d706f72702e)
        /usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc820046da8 sp=0xc820046d50
net.lookupIP(0xea0c40, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc820046e18 sp=0xc820046da8
net.glob.func16(0x104c5d0, 0xea0c40, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/hook.go:10 +0x4d fp=0xc820046e58 sp=0xc820046e18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc820046ed8 sp=0xc820046e58
internal/singleflight.(*Group).doCall(0x15e2840, 0xc820316d70, 0xea0c40, 0x9, 0xc820204140)
        /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc820046f88 sp=0xc820046ed8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820046f90 sp=0xc820046f88
created by internal/singleflight.(*Group).DoChan                                                                                                                       [36/1958]
        /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee

goroutine 1 [select]:
net.lookupIPDeadline(0xea0c40, 0x9, 0xeced6a181, 0x29413356, 0x15e37a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xe86630, 0x3, 0xea0c40, 0xf, 0xeced6a181, 0x29413356, 0x15e37a0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xe81f08, 0x4, 0xe86630, 0x3, 0xea0c40, 0xf, 0xeced6a181, 0xc829413356, 0x15e37a0, 0x0, ...)
        /usr/local/go/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc8202375e8, 0xe86630, 0x3, 0xea0c40, 0xf, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:216 +0x124
net.DialTimeout(0xe86630, 0x3, 0xea0c40, 0xf, 0x77359400, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:200 +0xa3
github.com/google/cadvisor/container/rkt.Client.func1()
        /home/fkoch/src/go/src/github.com/google/cadvisor/container/rkt/client.go:44 +0x59
sync.(*Once).Do(0x1608b20, 0x104bcc0)
        /usr/local/go/src/sync/once.go:44 +0xe4
github.com/google/cadvisor/container/rkt.Client(0x0, 0x0, 0x0, 0x0)
        /home/fkoch/src/go/src/github.com/google/cadvisor/container/rkt/client.go:79 +0x47
github.com/google/cadvisor/container/rkt.RktPath(0x0, 0x0, 0x0, 0x0)
        /home/fkoch/src/go/src/github.com/google/cadvisor/container/rkt/client.go:85 +0x48
github.com/google/cadvisor/manager.New(0xc8202f9a40, 0x7f134c4bbad8, 0x1608a68, 0xdf8475800, 0xc8202f9a01, 0xc8203498f0, 0x0, 0x0, 0x0, 0x0)
        /home/fkoch/src/go/src/github.com/google/cadvisor/manager/manager.go:144 +0x341
main.main()
        /home/fkoch/src/go/src/github.com/google/cadvisor/cadvisor.go:121 +0x57c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x15e3b00)
        /home/fkoch/src/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:882 +0x67
created by github.com/golang/glog.init.1
        /home/fkoch/src/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 58 [IO wait]:
net.runtime_pollWait(0x7f134c4bcc18, 0x72, 0xc8202b8000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82037a920, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82037a920, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82037a8c0, 0xc8202b8000, 0x1000, 0x1000, 0x0, 0x7f134eddf050, 0xc82000e1b0)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82013a1b8, 0xc8202b8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f134c4bccd8, 0xc82013a1b8, 0xc8202f2af8, 0xc8202b8000, 0x1000, 0x1000, 0x4082c3, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8203714e0, 0xc8202b8000, 0x1000, 0x1000, 0xc820197d1d, 0x0, 0x0)
        <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820072a80)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820072a80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8202f2a90)
        /usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 59 [select]:
net/http.(*persistConn).writeLoop(0xc8202f2a90)
        /usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:858 +0x10cb
```

**Comment by vishh** [comment]
Looks like its crashing on DNS resolution.

If you compiling on Unix and using go v1.5+, I'd expect cAdvisor to not
invoke cgo at all - More information https://golang.org/doc/go1.5#net

**Comment by timstclair** [comment]
cAdvisor and lots of it's dependencies use cgo:
https://github.com/google/cadvisor/blob/master/utils/procfs/jiffy.go
https://github.com/google/cadvisor/blob/master/utils/cpuload/netlink/defs.go
https://github.com/google/cadvisor/blob/master/Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp.go#L26
etc.

**Comment by f0** [comment]
@vishh @timstclair   yes i know this, i use the default build.sh to build the binary and i think this should be work per default, or not?

**Comment by vishh** [comment]
It should & it does for me.

```shell
$ go version
go version go1.6.2 linux/amd64
```

**Comment by f0** [comment]
@vishh  ok then the question is why does this not work for me? I use a default go 1.6.2 installation and the default cadvisor build script

**Comment by f0** [comment]
@vishh hm the cadvisor binary is not really a static binary on my system .... build with the upstream build.sh

~/src/go/src/github.com/google/cadvisor (master>) % ldd cadvisor
	linux-vdso.so.1 (0x00007ffe4830a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f99c8687000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f99c82e5000)
	/lib64/ld-linux-x86-64.so.2 (0x000056161c967000)

**Comment by f0** [comment]
@vishh  ok this is wired, on my local system (cadvisor was build on this) it does work without problems
if i try this on CoreOS it breaks with the error above

**Comment by vishh** [comment]
cc @sjpotter

**Comment by sjpotter** [comment]
I'll see if I can test this later

**Comment by f0** [comment]
my local system is 
```
NAME=openSUSE
VERSION="Tumbleweed"
VERSION_ID="20160520"
PRETTY_NAME="openSUSE Tumbleweed (20160520) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:20160520"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
ID_LIKE="suse"
```

**Comment by sjpotter** [comment]
no longer working on rkt/cadvisor stuff.    someone else would have to attack it.

**Comment by dims** [comment]
Closing this issue as it has been open since before January 1, 2024. If this is still relevant, please feel free to reopen or create a new issue.
