### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by tomqwu** [google/cadvisor#1646]
Getting the following errors with google/cadvisor:v0.25.0 - f9ba08bafdea
```
docker run --privileged=true --volume=/cgroup:/cgroup:ro  --volume=/:/rootfs:ro   --volume=/var/run:/var/run:rw   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro   --publish=8080:8080   --detach=true   --name=cadvisor  google/cadvisor:v0.25.0
```

```
I0503 03:36:32.743254       1 storagedriver.go:50] Caching stats in memory for 2m0s
I0503 03:36:32.743460       1 manager.go:143] cAdvisor running in container: "/docker/cb4f08c09d6bca1e5664580b8d4a6c73884f89e2ec8b8a549324ca9b4d343a1a"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f1b6a5911ed]

runtime stack:
runtime.throw(0xcdd37b, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 28 [syscall, locked to thread]:
runtime.cgocall(0xa551f0, 0xc42021b5f8, 0xc400000000)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42021b5b0 sp=0xc42021b570
net._C2func_getaddrinfo(0x7f1b5c0008c0, 0x0, 0xc4202261e0, 0xc42010e0b0, 0x0, 0x0, 0x0)
	??:0 +0x68 fp=0xc42021b5f8 sp=0xc42021b5b0
net.cgoLookupIPCNAME(0xcc7b5a, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:146 +0x37c fp=0xc42021b718 sp=0xc42021b5f8
net.cgoIPLookup(0xc420114fc0, 0xcc7b5a, 0x9)
	/usr/local/go/src/net/cgo_unix.go:198 +0x4d fp=0xc42021b7a8 sp=0xc42021b718
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42021b7b0 sp=0xc42021b7a8
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:208 +0xb4

goroutine 1 [select]:
net.lookupIPContext(0x12c2500, 0xc420114f00, 0xcc7b5a, 0x9, 0x0, 0x0, 0x0, 0x0, 0xc4203f5390)
	/usr/local/go/src/net/lookup.go:122 +0x7bc
net.internetAddrList(0x12c2500, 0xc420114f00, 0xcbcb90, 0x3, 0xcc7b5a, 0xf, 0x0, 0x0, 0x0, 0xed09b4740, ...)
	/usr/local/go/src/net/ipsock.go:241 +0x5e0
net.resolveAddrList(0x12c2500, 0xc420114f00, 0xcbd267, 0x4, 0xcbcb90, 0x3, 0xcc7b5a, 0xf, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:179 +0x106
net.(*Dialer).DialContext(0xc4203f5790, 0x12c24c0, 0xc4200123d8, 0xcbcb90, 0x3, 0xcc7b5a, 0xf, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:329 +0x238
net.(*Dialer).Dial(0xc4203f5790, 0xcbcb90, 0x3, 0xcc7b5a, 0xf, 0x1, 0xc42005e120, 0x506094, 0x502595)
	/usr/local/go/src/net/dial.go:282 +0x75
net.DialTimeout(0xcbcb90, 0x3, 0xcc7b5a, 0xf, 0x77359400, 0xf, 0xc420224610, 0x7, 0xc420387ce0)
	/usr/local/go/src/net/dial.go:268 +0x9d
github.com/google/cadvisor/container/rkt.Client.func1()
	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/rkt/client.go:44 +0x69
sync.(*Once).Do(0x1369b30, 0xd3aac0)
	/usr/local/go/src/sync/once.go:44 +0xdb
github.com/google/cadvisor/container/rkt.Client(0xc4202b0380, 0x1d, 0x0, 0x0)
	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/rkt/client.go:79 +0x39
github.com/google/cadvisor/container/rkt.RktPath(0xc4202a4368, 0x6, 0xc4203b36e0, 0x1a)
	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/rkt/client.go:85 +0x29
github.com/google/cadvisor/manager.New(0xc420385940, 0x12c6520, 0x1369a90, 0xdf8475800, 0x12b9c01, 0xc42038a120, 0xc42038a6c0, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/manager/manager.go:149 +0x18b
main.main()
	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/cadvisor.go:127 +0x1e0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [chan receive]:
github.com/google/cadvisor/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x13459c0)
	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:882 +0x7a
created by github.com/google/cadvisor/vendor/github.com/golang/glog.init.1
	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 27 [select]:
net.cgoLookupIP(0x12c2500, 0xc420114f00, 0xcc7b5a, 0x9, 0x683a5d64656c6261, 0x6569662c7265766f, 0xc42021b728, 0x1, 0x1, 0xc42021b78c)
	/usr/local/go/src/net/cgo_unix.go:209 +0x2f5
net.lookupIP(0x12c2500, 0xc420114f00, 0xcc7b5a, 0x9, 0x6f663a5d64656c62, 0x6c6569662c737563, 0x7369645b74657364, 0x2e205d64656c6261, 0x616665642d6e7462)
	/usr/local/go/src/net/lookup_unix.go:70 +0xf9
net.glob..func11(0x12c2500, 0xc420114f00, 0xd3ba38, 0xcc7b5a, 0x9, 0xc42021b710, 0xc42021b6d8, 0x43fa75, 0xc42021b6e8, 0x935a48)
	/usr/local/go/src/net/hook.go:19 +0x52
net.lookupIPContext.func1(0x0, 0x10002, 0xc42021b78c, 0xc42021b788)
	/usr/local/go/src/net/lookup.go:119 +0x5c
internal/singleflight.(*Group).doCall(0x13443d0, 0xc4203895e0, 0xcc7b5a, 0x9, 0xc420387dd0)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x3c
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x339

goroutine 24 [IO wait]:
net.runtime_pollWait(0x7f1b6b49e790, 0x72, 0x3)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420354300, 0x72, 0xc42002f9d0, 0xc420012140)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420354300, 0x12bc800, 0xc420012140)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4203542a0, 0xc42035c000, 0x1000, 0x1000, 0x0, 0x12bc800, 0xc420012140)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42010e088, 0xc42035c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420132b00, 0xc42035c000, 0x1000, 0x1000, 0x4d4f70, 0xc42002fb58, 0x4081fd)
	/usr/local/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc420114c60)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc420114c60, 0x1, 0xc42002fbbd, 0x1, 0x0, 0xc420284120, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420132b00)
	/usr/local/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9

goroutine 25 [select]:
net/http.(*persistConn).writeLoop(0xc420132b00)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e
```

```
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

```
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

**Comment by tomqwu** [comment]
Interestingly if I remove `--volume=/var/run:/var/run:rw`, then container runs normally.

**Comment by dashpole** [comment]
this looks like the same as #1481

**Comment by dims** [comment]
Closing this issue as it has been open since before January 1, 2024. If this is still relevant, please feel free to reopen or create a new issue.
