### ISSUE TITLE
[ feature ][ could make cadvisor client to be alone package? ]

### ISSUE THREAD

**Issue by gogeof** [google/cadvisor#1875]
### Version
- git clone the latest code today use this command:
```bash
go get github.com/google/cadvisor
```

### What happen?
Today I try to use cadvisor, and import "github.com/google/cadvisor/client", and follow the Readme.md, add this code in my project
```golang
        key := fmt.Sprintf("http://%s:%d", masters[hostip].HostIP, 4194)
	cClient, err := client.NewClient(key)
	if err != nil {
		log.Printf("get cadvisor client by %s, but failed: %v", key, err)
		continue
	}

	// 获取机器信息
	m, err := cClient.MachineInfo()
	if err != nil {
		log.Printf("get machine info failed: %v", err)
		continue
	}
```
but get error when compile
```bash
/tmp/___go_build_main_go flag redefined: log_dir
panic: /tmp/___go_build_main_go flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc42005e120, 0x1a97aa0, 0xc4203f50a0, 0x12bb7b2, 0x7, 0x12e6c08, 0x2f)
	/software/golang/go-v1.9.2/src/flag/flag.go:793 +0x5e1
flag.(*FlagSet).StringVar(0xc42005e120, 0xc4203f50a0, 0x12bb7b2, 0x7, 0x0, 0x0, 0x12e6c08, 0x2f)
	/software/golang/go-v1.9.2/src/flag/flag.go:696 +0x8b
flag.(*FlagSet).String(0xc42005e120, 0x12bb7b2, 0x7, 0x0, 0x0, 0x12e6c08, 0x2f, 0xc4203adf20)
	/software/golang/go-v1.9.2/src/flag/flag.go:709 +0x8b
flag.String(0x12bb7b2, 0x7, 0x0, 0x0, 0x12e6c08, 0x2f, 0xed84f9)
	/software/golang/go-v1.9.2/src/flag/flag.go:716 +0x69
github.com/google/cadvisor/vendor/github.com/golang/glog.init()
	/home/gogeof/work/gopath/src/github.com/google/cadvisor/vendor/github.com/golang/glog/glog_file.go:41 +0x14a
github.com/google/cadvisor/client.init()
	<autogenerated>:1 +0x71
ufleet/go-cluster-daemon/do.init()
	<autogenerated>:1 +0x70
main.init()
	<autogenerated>:1 +0x44
```

### What expected?
- could use cadvisor client alone

**Comment by dashpole** [comment]
I think the log_dir flag comes from glog, which we dont control.  Are you adding a flag to your application that has the same name?
As far as being able to vendor only the client, the client needs the apis (stored in `info/`) to parse output.

**Comment by gogeof** [comment]
@dashpole yes, you're right, in info/v2, there also use glog package, and will cause the problem if want to v2. But if really want make cadvisor client to be independent, there must be some ways. So, what do you think?
