### ISSUE TITLE
Cannot create cadvisor container with got "could not detect clock speed" error

### ISSUE THREAD

**Issue by TerrenceXu** [google/cadvisor#2237]
Hi All,

I followed the cadvisor user guide: https://github.com/google/cadvisor/blob/master/README.md to run cadvisor docker image as below:

`docker run -it --rm   --volume=/:/rootfs:ro   --volume=/var/run:/var/run:ro   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro   --volume=/dev/disk/:/dev/disk:ro   --publish=8080:8080   --name=cadvisor   google/cadvisor:latest`
 
Then i created container failed with got the error as below:
`F0509 14:40:45.882711       1 cadvisor.go:146] Failed to create a Container Manager: could not detect clock speed from output: ""`

I checked the cpuClock speed regexp code as below:
`cpuClockSpeedMHz     = regexp.MustCompile(`(?:cpu MHz|clock)\s*:\s*([0-9]+\.[0-9]+)(?:MHz)?`)`

Actually i also cannot got any information from `/proc/cpuinfo |grep -E '(?:cpu MHz|clock)\s*:\s*([0-9]+\.[0-9]+)(?:MHz)?'`

Is it a bug? Do you know the reason?

My host is Ubuntu 18.04 with 4.20 kernel.

**Comment by dashpole** [comment]
Does `/proc/cpuinfo` exist?  What does it contain?  This just means your kernel is likely reporting the cpu clock speed differently from what we expect, and we probably need to update our regexp for it.

**Comment by TerrenceXu** [comment]
@dashpole , the example as below, thanks!
root@terrence-host:~# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 78
model name      : Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz
stepping        : 3
microcode       : 0xc6
cpu MHz         : 2700.006
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
……

**Comment by TerrenceXu** [comment]
If I run google/cadvisor container without "--volume=/:/rootfs:ro", it can be created without the clock detect issue, but with the error information as below:
```
"E0513 13:58:19.800523       1 info.go:140] Failed to get system UUID: open /etc/machine-id: no such file or directory
W0513 13:58:19.801783       1 info.go:53] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
W0513 13:58:19.812254       1 manager.go:349] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory".
```
The error is make sense, just for debug. :)

**Comment by dashpole** [comment]
I don't _think_ this is an issue with `/proc/cpuinfo`.  The line "cpu MHz : 2700.006" matches the regexp the container manager is using: https://regex101.com/r/cIi3T0/1.

Maybe the output `could not detect clock speed from output: ""` means it couldn't open the file correctly?  Or is the /proc/cpuinfo file inside the cAdvisor container different from the one on the host?

**Comment by VasantSachdewa** [comment]
@TerrenceXu  did you get this working?

**Comment by vashian** [comment]
Any progress on this? I'm getting the same error on mac m1

**Comment by dakotak** [comment]
+1

**Comment by ngannguyen2294** [comment]
Any updates on this?

**Comment by corymacd** [comment]
+1

**Comment by pierrot7** [comment]
+1 on Mac m1 and pro m2, any updates ?

**Comment by fungiboletus** [comment]
Using lima/colima VMs on a ARM Mac, the `/proc/cpuinfo` file looks like this:

```
processor	: 0
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint
CPU implementer	: 0x00
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0x000
CPU revision	: 0

processor	: 1
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint
CPU implementer	: 0x00
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0x000
CPU revision	: 0

processor	: 2
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint
CPU implementer	: 0x00
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0x000
CPU revision	: 0

processor	: 3
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint
CPU implementer	: 0x00
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0x000
CPU revision	: 0
```

**Comment by fungiboletus** [comment]
In my case the problem was that I was running the amd64 image on a qemu emulated VM.

Using the latest version and specifying `--platform=linux/arm64` fixed the problem.

**Comment by frapsky** [comment]
Try this: https://github.com/google/cadvisor/issues/2838

**Comment by kbhatt-lavamedia** [comment]
Still seeing this issue even on AWS Linux instance

sudo docker run  --volume=/var/run:/var/run:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8081:8080  --name=cadvisor   --privileged   --device=/dev/kmsg  gcr.io/cadvisor/cadvisor:latest 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
W0707 09:47:38.908101       1 manager.go:159] Cannot detect current cgroup on cgroup v2
F0707 09:47:39.145684       1 cadvisor.go:175] Failed to create a manager: could not detect clock speed from output: "processor\t: 0\nBogoMIPS\t: 243.75\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs\nCPU implementer\t: 0x41\nCPU architecture: 8\nCPU variant\t: 0x3\nCPU part\t: 0xd0c\nCPU revision\t: 1\n\nprocessor\t: 1\nBogoMIPS\t: 243.75\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs\nCPU implementer\t: 0x41\nCPU architecture: 8\nCPU variant\t: 0x3\nCPU part\t: 0xd0c\nCPU revision\t: 1\n\n"
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc00038e400, 0x27e, 0x3a0)
        /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x2441740, 0xc000000003, 0x0, 0x0, 0xc0001e3420, 0x2375833, 0xb, 0xaf, 0x0)
        /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x19d
k8s.io/klog/v2.(*loggingT).printf(0x2441740, 0x3, 0x0, 0x0, 0x16bcdd4, 0x1e, 0xc00060dea0, 0x1, 0x1)
        /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
        /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456
main.main()
        /go/src/github.com/google/cadvisor/cmd/cadvisor.go:175 +0x3b8

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 21 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2441740)
        /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:416 +0xd6

goroutine 26 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000fc180)
        /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x100
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68

goroutine 29 [IO wait]:
internal/poll.runtime_pollWait(0x4002ed1ea8, 0x72, 0xffffffffffffffff)
        /usr/lib/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000fc898, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000fc880, 0xc0001ef000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0000fc880, 0xc0001ef000, 0x1000, 0x1000, 0x43491c, 0xc00006bb20, 0x45f2a0)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010218, 0xc0001ef000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:184 +0x68
net/http.(*persistConn).Read(0xc0000b70e0, 0xc0001ef000, 0x1000, 0x1000, 0xc000136180, 0xc00006bc20, 0x408305)
        /usr/lib/go/src/net/http/transport.go:1758 +0x75
bufio.(*Reader).fill(0xc00008eb40)
        /usr/lib/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc00008eb40, 0x1, 0x0, 0x0, 0x1, 0xc000136a00, 0x0)
        /usr/lib/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0000b70e0)
        /usr/lib/go/src/net/http/transport.go:1911 +0x1d6
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1580 +0xb0d

goroutine 30 [select]:
net/http.(*persistConn).writeLoop(0xc0000b70e0)
        /usr/lib/go/src/net/http/transport.go:2210 +0x123
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1581 +0xb32

**Comment by gavink97** [comment]
> Still seeing this issue even on AWS Linux instance. And I tried with all options to bare minimum.. nothin works unfortunately.
> 
> full command tried was `sudo docker run \ --volume=/:/rootfs:ro \ --volume=/var/run:/var/run:ro \ --volume=/sys:/sys:ro \ --volume=/var/lib/docker/:/var/lib/docker:ro \ --volume=/dev/disk/:/dev/disk:ro \ --publish=8080:8080 \ --detach=true \ --name=cadvisor \ --privileged \ --device=/dev/kmsg \ --platform=linux/amd64 gcr.io/cadvisor/cadvisor:latest`
> 
> `sudo docker run --volume=/var/run:/var/run:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8081:8080 --name=cadvisor --privileged --device=/dev/kmsg gcr.io/cadvisor/cadvisor:latest` WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested W0707 09:47:38.908101 1 manager.go:159] Cannot detect current cgroup on cgroup v2 F0707 09:47:39.145684 1 cadvisor.go:175] Failed to create a manager: could not detect clock speed from output: "processor\t: 0\nBogoMIPS\t: 243.75\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs\nCPU implementer\t: 0x41\nCPU architecture: 8\nCPU variant\t: 0x3\nCPU part\t: 0xd0c\nCPU revision\t: 1\n\nprocessor\t: 1\nBogoMIPS\t: 243.75\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs\nCPU implementer\t: 0x41\nCPU architecture: 8\nCPU variant\t: 0x3\nCPU part\t: 0xd0c\nCPU revision\t: 1\n\n" goroutine 1 [running]: k8s.io/klog/v2.stacks(0xc000010001, 0xc00038e400, 0x27e, 0x3a0) /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb8 k8s.io/klog/v2.(*loggingT).output(0x2441740, 0xc000000003, 0x0, 0x0, 0xc0001e3420, 0x2375833, 0xb, 0xaf, 0x0) /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x19d k8s.io/klog/v2.(*loggingT).printf(0x2441740, 0x3, 0x0, 0x0, 0x16bcdd4, 0x1e, 0xc00060dea0, 0x1, 0x1) /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17a k8s.io/klog/v2.Fatalf(...) /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456 main.main() /go/src/github.com/google/cadvisor/cmd/cadvisor.go:175 +0x3b8
> 
> goroutine 20 [syscall]: os/signal.signal_recv(0x0) /usr/lib/go/src/runtime/sigqueue.go:147 +0x9c os/signal.loop() /usr/lib/go/src/os/signal/signal_unix.go:23 +0x22 created by os/signal.init.0 /usr/lib/go/src/os/signal/signal_unix.go:29 +0x41
> 
> goroutine 21 [chan receive]: k8s.io/klog/v2.(*loggingT).flushDaemon(0x2441740) /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1131 +0x8b created by k8s.io/klog/v2.init.0 /go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:416 +0xd6
> 
> goroutine 26 [select]: go.opencensus.io/stats/view.(*worker).start(0xc0000fc180) /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x100 created by go.opencensus.io/stats/view.init.0 /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68
> 
> goroutine 29 [IO wait]: internal/poll.runtime_pollWait(0x4002ed1ea8, 0x72, 0xffffffffffffffff) /usr/lib/go/src/runtime/netpoll.go:184 +0x55 internal/poll.(*pollDesc).wait(0xc0000fc898, 0x72, 0x1000, 0x1000, 0xffffffffffffffff) /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x45 internal/poll.(*pollDesc).waitRead(...) /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92 internal/poll.(*FD).Read(0xc0000fc880, 0xc0001ef000, 0x1000, 0x1000, 0x0, 0x0, 0x0) /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x1cf net.(*netFD).Read(0xc0000fc880, 0xc0001ef000, 0x1000, 0x1000, 0x43491c, 0xc00006bb20, 0x45f2a0) /usr/lib/go/src/net/fd_unix.go:202 +0x4f net.(*conn).Read(0xc000010218, 0xc0001ef000, 0x1000, 0x1000, 0x0, 0x0, 0x0) /usr/lib/go/src/net/net.go:184 +0x68 net/http.(*persistConn).Read(0xc0000b70e0, 0xc0001ef000, 0x1000, 0x1000, 0xc000136180, 0xc00006bc20, 0x408305) /usr/lib/go/src/net/http/transport.go:1758 +0x75 bufio.(*Reader).fill(0xc00008eb40) /usr/lib/go/src/bufio/bufio.go:100 +0x103 bufio.(*Reader).Peek(0xc00008eb40, 0x1, 0x0, 0x0, 0x1, 0xc000136a00, 0x0) /usr/lib/go/src/bufio/bufio.go:138 +0x4f net/http.(*persistConn).readLoop(0xc0000b70e0) /usr/lib/go/src/net/http/transport.go:1911 +0x1d6 created by net/http.(*Transport).dialConn /usr/lib/go/src/net/http/transport.go:1580 +0xb0d
> 
> goroutine 30 [select]: net/http.(*persistConn).writeLoop(0xc0000b70e0) /usr/lib/go/src/net/http/transport.go:2210 +0x123 created by net/http.(*Transport).dialConn /usr/lib/go/src/net/http/transport.go:1581 +0xb32

Are you still having this issue?

I managed to solve this by referencing the latest tag's version number "gcr.io/cadvisor/cadvisor:v0.47.2 " instead of "gcr.io/cadvisor/cadvisor:latest".

In my case I needed the latest arm version however, if you need the latest amd64 version I would try referencing that.

You are able to see the release tags under the release section on Github.
[https://github.com/google/cadvisor/releases/tag/v0.47.2](url)

`  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    privileged: true
    ports:
      - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    depends_on:
      - mysql`

**Comment by konrad-sol** [comment]
+1 on Mac m2, kind v0.20.0

**Comment by dims** [comment]
Closing this issue as it has been open since before January 1, 2024. If this is still relevant, please feel free to reopen or create a new issue.
