### ISSUE TITLE
Random "http: panic serving" during api/v2.0/stats requests

### ISSUE THREAD

**Issue by PaulAnnekov** [google/cadvisor#2281]
**Versions:** `google/cadvisor:canary` and `k8s.gcr.io/cadvisor:v0.33.0`
**Environment:** cAdvisors are in docker containers in k8s DaemonSet

Each 5 seconds I make the following request:
`http://some_ip:some_port/api/v2.0/stats?type=docker&recursive=true`

And sometimes instead of a correct response I get `socket hang up` in http client + this error in cAdvisor logs:
```
E0802 14:48:13.540406       1 versions.go:367] Error calling GetRequestedContainersInfo: partial failures: ["/kubepods/burstable/pod8889f49b-b534-11e9-8380-42010aa40149/0913d45b29147c3a821084271a59e913e8a0dfd4adbd3857dc7aed37e110c051": containerDataToContainerInfo: unable to find data in memory cache]
2019/08/02 14:48:13 http: panic serving 10.28.0.3:38648: runtime error: invalid memory address or nil pointer dereference
goroutine 1087 [running]:
net/http.(*conn).serve.func1(0xc0008da460)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x10861a0, 0x1bb1340)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/google/cadvisor/info/v2.DeprecatedStatsFromV1(0x0, 0xc000c27ef0, 0xc0003e3c80, 0x7c)
        /go/src/github.com/google/cadvisor/info/v2/conversion.go:158 +0x3a
github.com/google/cadvisor/api.(*version2_0).HandleRequest(0x1c9aaf0, 0xc0004d444e, 0x5, 0xc0002e2cc0, 0x0, 0x0, 0x135bae0, 0xc0001ae600, 0x134cb00, 0xc00034f880, ...)
        /go/src/github.com/google/cadvisor/api/versions.go:371 +0x41f
github.com/google/cadvisor/api.handleRequest(0xc0000f49f0, 0x135bae0, 0xc0001ae600, 0x134cb00, 0xc00034f880, 0xc000367100, 0x0, 0x0)
        /go/src/github.com/google/cadvisor/api/handler.go:121 +0x5af
github.com/google/cadvisor/api.RegisterHandlers.func1(0x134cb00, 0xc00034f880, 0xc000367100)
        /go/src/github.com/google/cadvisor/api/handler.go:51 +0x5e
net/http.HandlerFunc.ServeHTTP(0xc0002d8540, 0x134cb00, 0xc00034f880, 0xc000367100)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000f4900, 0x134cb00, 0xc00034f880, 0xc000367100)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.(*ServeMux).ServeHTTP(0xc00055e030, 0x134cb00, 0xc00034f880, 0xc000367100)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00044b110, 0x134cb00, 0xc00034f880, 0xc000367100)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0008da460, 0x134d940, 0xc000c93c80)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by PaulAnnekov** [comment]
I'm doing 3 immediate repeats (~100ms delay) on error and container is always different here:
`...Error calling GetRequestedContainersInfo: partial failures: ["/kubepods/burstable/pod8889f49b-b534-11e9-8380-42010aa40149/0913d45b29147c3a821084271a59e913e8a0dfd4adbd3857dc7aed37e110c051": containerDataToContainerInfo: unable to find data in memory cache]`

**Comment by dims** [comment]
Closing this issue as it has been open since before January 1, 2024. If this is still relevant, please feel free to reopen or create a new issue.
