### ISSUE TITLE
Non-volatile memory - segfault on capacity retrival

### ISSUE THREAD

**Issue by iwankgb** [google/cadvisor#2457]
Following error occurred:
```
I0401 15:37:03.119118    8407 manager.go:200] Version: {KernelVersion:3.10.0-1062.12.1.el7.x86_64 ContainerOsVersion:CentOS Linux 7 (Core) DockerVersion:1.13.1 DockerAPIVersion:1.26 CadvisorVersion:v0.36.0.72+fd3fca4f5f6a83 CadvisorRevision:fd3fca4}
I0401 15:37:03.154724    8407 factory.go:369] Registering Docker factory
I0401 15:37:03.154784    8407 factory.go:55] Registering systemd factory
I0401 15:37:03.155159    8407 factory.go:101] Registering Raw factory
I0401 15:37:03.316050    8407 cadvisor.go:196] Starting cAdvisor version: v0.36.0.72+fd3fca4f5f6a83-fd3fca4 on port 8080
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10000000000 pc=0x7f90f5eeab20]

runtime stack:
runtime.throw(0x13a95a2, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 477 [syscall]:
runtime.cgocall(0x10b0b30, 0xc0006f4a68, 0xc000870601)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0006f4a38 sp=0xc0006f4a00 pc=0x405acb
github.com/google/cadvisor/machine._Cfunc_nvm_get_nvm_capacities(0xc0005ceb00, 0xc000000000)
        _cgo_gotypes.go:304 +0x49 fp=0xc0006f4a68 sp=0xc0006f4a38 pc=0x93ce59
github.com/google/cadvisor/machine.getNVMCapacities(0xc0006f4b30, 0xc001e05ac0, 0xc002a9d9e0, 0x0)
        /home/iwan/go/src/github.com/google/cadvisor/machine/machine_libipmctl.go:68 +0x44 fp=0xc0006f4ae0 sp=0xc0006f4a68 pc=0x93d4d4
github.com/google/cadvisor/machine.GetNVMInfo(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/iwan/go/src/github.com/google/cadvisor/machine/machine_libipmctl.go:88 +0x8d fp=0xc0006f4b98 sp=0xc0006f4ae0 pc=0x93d6bd
github.com/google/cadvisor/machine.Info(0x1574ee0, 0x205ffa0, 0x1569a00, 0xc0002e6360, 0xed6165b01, 0x2042c40, 0x1f, 0x12aea7)
        /home/iwan/go/src/github.com/google/cadvisor/machine/info.go:80 +0x1b2 fp=0xc0006f4ee8 sp=0xc0006f4b98 pc=0x939c12
github.com/google/cadvisor/manager.(*manager).updateMachineInfo(0xc0001dc240, 0xc0009183c0)
        /home/iwan/go/src/github.com/google/cadvisor/manager/manager.go:322 +0x11b fp=0xc0006f4fd0 sp=0xc0006f4ee8 pc=0x9c186b
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0006f4fd8 sp=0xc0006f4fd0 pc=0x461c51
created by github.com/google/cadvisor/manager.(*manager).Start
        /home/iwan/go/src/github.com/google/cadvisor/manager/manager.go:295 +0x50d

```

Build command:
```
GO_FLAGS="-tags=libipmctl,netgo,libpfm" make build
```

cAdvisor command:
```
sudo ./cadvisor -v 1 -profiling
```

**Comment by iwankgb** [comment]
It seems that `SIGSEGV` is caused by calling:

1. `nvm_init()`
2. `nvm_get_capacities()`
3. `nvm_uninit()`
4. `nvm_init()`
5. `nvm_get_capacities()`

As if `nvm_uninit()` unset state that `nvm_init()` can't bring back.
