### ISSUE TITLE
v0.39.1 crashes on arm

### ISSUE THREAD

**Issue by logopk** [google/cadvisor#2877]
I have built cadvisor with buildx for armv7 for my Raspberry Pi 3b+ but it fails to start:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x130a4]

goroutine 67 [running]:
github.com/google/cadvisor/manager.(*containerData).updateStats(0x3aa1680, 0x35678066, 0xc0220fc0)
        /go/src/github.com/google/cadvisor/manager/container.go:675 +0x7c
github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0x3aa1680, 0x3b02000, 0x5f5e100, 0x0, 0x38f4000)
        /go/src/github.com/google/cadvisor/manager/container.go:586 +0xe8
github.com/google/cadvisor/manager.(*containerData).housekeeping(0x3aa1680)
        /go/src/github.com/google/cadvisor/manager/container.go:534 +0x200
created by github.com/google/cadvisor/manager.(*containerData).Start
        /go/src/github.com/google/cadvisor/manager/container.go:122 +0x2c

```
Any idea what I could do to fix this? Could it be that runc on the host is not current enough?

**Comment by logopk** [comment]
```
runc --version
runc version 1.0.0-rc93
commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
spec: 1.0.2-dev
go: go1.13.15
libseccomp: 2.4.3

```

**Comment by kolyshkin** [comment]
Line numbers in the panic message seem to be off (not matching the v0.39.1 release)

**Comment by logopk** [comment]
ooops. Apparently my Dockerfile pulled always master (even though I passed the tag version). Fixed and running.

Thanks.
