### ISSUE TITLE
Use of atomic.Load64 against unaligned field causes panic on armv7

### ISSUE THREAD

**Issue by brandond** [google/cadvisor#3033]
The atomic operation at https://github.com/google/cadvisor/blob/99d3532c47137cd9241a8415e4aef2600672f7c5/manager/container.go#L676 
 (added by https://github.com/google/cadvisor/pull/2829) performs an unaligned load on 32bit systems, or at least armv7l. This results in a panic:

```
panic: unaligned 64-bit atomic operation

goroutine 13904 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0xfb9a2ec)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:286 +0x14
github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager.(*containerData).updateStats(0xfb9a180)
        /go/src/github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager/container.go:676 +0x438
github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0xfb9a180, 0x12608b00, 0x5f5e100)
        /go/src/github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager/container.go:587 +0x104
github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager.(*containerData).housekeeping(0xfb9a180)
        /go/src/github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager/container.go:535 +0x3c0
created by github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager.(*containerData).Start
        /go/src/github.com/rancher/k3s/vendor/github.com/google/cadvisor/manager/container.go:122 +0x2c
```

This same code works fine on arm64 and amd64.

**Comment by brandond** [comment]
cc @iwankgb @kragniz

**Comment by martadinata666** [comment]
#3029

**Comment by brandond** [comment]
Thanks, didn't find that one when searching!
