### ISSUE TITLE
panic with flags when built using Go 1.21.x

### ISSUE THREAD

**Issue by mythi** [google/cadvisor#3403]
```
$ go env GOVERSION
go1.21.1
$ git rev-parse HEAD
28d5bdd0c25de48109af223d3d18db253f6188d5
$ make build
>> building assets
>> building binaries
>> building cadvisor
$ _output/cadvisor -version
panic: flag v set at /home/mylinen/tmp/cadvisor/cmd/cadvisor.go:105 before being defined

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0001cc150, {0x18e5460, 0x2301530}, {0x18d6a20, 0x1}, {0x165bc51, 0x22})
	/usr/local/go/src/flag/flag.go:1031 +0x33a
k8s.io/klog/v2.InitFlags.func1(0xc0001ffe60?)
	/home/mylinen/go/pkg/mod/k8s.io/klog/v2@v2.100.1/klog.go:437 +0x31
flag.(*FlagSet).VisitAll(0x1?, 0xc000543c78)
	/usr/local/go/src/flag/flag.go:458 +0x42
k8s.io/klog/v2.InitFlags(0x1395c40?)
	/home/mylinen/go/pkg/mod/k8s.io/klog/v2@v2.100.1/klog.go:436 +0x45
main.main()
	/home/mylinen/tmp/cadvisor/cmd/cadvisor.go:109 +0x36
```

Go 1.21.x changes the package initialization order and it looks
https://github.com/google/cadvisor/blob/28d5bdd0c25de48109af223d3d18db253f6188d5/cmd/cadvisor.go#L105

breaks with that?

**Comment by eero-t** [comment]
See https://github.com/google/cadvisor/pull/3384 and https://github.com/google/cadvisor/pull/3387.

**Comment by mythi** [comment]
closing as a know issue. I only looked for open issues and did not check for open PRs
