### ISSUE TITLE
cAdvisor Crashes Getting CPU Load

### ISSUE THREAD

**Issue by vmarmol** [google/cadvisor#457]
Every now and then I get the following stacktrace while handling CPU load (this is in HEAD).

```
goroutine 212 [running]:
bufio.(*Reader).Read(0x4c208048f60, 0x4c208417700, 0x10, 0x10, 0x4c20860ccc0, 0x0, 0x0)
	/usr/lib/google-golang/src/bufio/bufio.go:181 +0x3d8
io.ReadAtLeast(0x7f0745b79470, 0x4c208048f60, 0x4c208417700, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/io/io.go:298 +0xf1
io.ReadFull(0x7f0745b79470, 0x4c208048f60, 0x4c208417700, 0x10, 0x10, 0x10, 0x0, 0x0)
	/usr/lib/google-golang/src/io/io.go:316 +0x6d
encoding/binary.Read(0x7f0745b79470, 0x4c208048f60, 0x7f0745b76678, 0xf0b068, 0x7b8ca0, 0x4c20860cc00, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/binary/binary.go:216 +0x13b0
github.com/google/cadvisor/utils/cpuload.(*Connection).ReadMessage(0x4c2080b7650, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/utils/cpuload/conn.go:88 +0x110
github.com/google/cadvisor/utils/cpuload.getLoadStats(0x4c2081e0019, 0x22, 0x4c2080b7650, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/utils/cpuload/netlink.go:231 +0x165
github.com/google/cadvisor/utils/cpuload.(*CpuLoadReader).GetCpuLoad(0x4c20802b6d0, 0x4c2081ed440, 0x5a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/utils/cpuload/cpuload.go:67 +0x2f8
github.com/google/cadvisor/manager.(*containerData).updateStats(0x4c208097680, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/manager/container.go:243 +0x1f2
github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0x4c208097680)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/manager/container.go:205 +0x2e
github.com/google/cadvisor/manager.(*containerData).housekeeping(0x4c208097680)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/manager/container.go:167 +0x205
created by github.com/google/cadvisor/manager.(*containerData).Start
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/manager/container.go:60 +0x44
```

**Comment by rjnagal** [comment]
Is that a panic or error? It looks like it is waiting for kernel to push some data to the netlink message queue. Is that timing out?

**Comment by vmarmol** [comment]
This is a panic.

**Comment by rjnagal** [comment]
Can you add the panic string - out of bound error?

**Comment by vmarmol** [comment]
Ah yes, sorry:

```
panic: runtime error: slice bounds out of range
```

**Comment by vishh** [comment]
Seems to be a dup of #452

**Comment by vmarmol** [comment]
I believe it is. Closing in favor of that. Note that the error paths don't seem to be triggered.

**Comment by rjnagal** [comment]
binary.Read is not returning, so the error paths are not going to be
triggered. I'll look at it today.
